language: php

branches:
  only:
    - master

php: 
  - '7.3'

env:
  - DATABASE_URL=mysql://root:@127.0.0.1:3306/oai

services: 
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required

install:
  - composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader
  - npm install
  - npm run build

cache:
  directories:
    - "vendor"
    - "node_modules"

script: 
  - bin/console doctrine:database:create
  - bin/console doctrine:schema:update --force
  - bin/console doctrine:fixtures:load --append
  - bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
