language: php

branches:
  only:
    - master

php: 
  - '7.3'

env:
  - DATABASE_URL=mysql://root:@127.0.0.1:3306/oai

services: 
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required

install:
  - composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader
  - npm i npm@latest -g && npm install && npm run build
  - bin/console d:d:c && bin/console d:s:u --force && bin/console d:f:l --append

cache:
  directories:
    - "vendor"
    - "node_modules"

script: 
  - bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
