language: php

branches:
  only:
    - master

php: 
  - '7.3'

env:
  - DATABASE_URL=mysql://root:@127.0.0.1:3306/oai

services: 
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required

install:
  - travis_retry composer install --no-interaction --no-suggest

script: 
  - bin/console doctrine:database:create
  - bin/console doctrine:schema:update --force
  - bin/console doctrine:fixtures:load --append
  - bin/console lint:twig templates
  - bin/console lint:yaml templates
	- vendor/bin/phpcs --standard=PSR1  src --ignore=./src/Kernel.php
	- vendor/bin/phpcs --standard=PSR2  src --ignore=./src/Kernel.php
	- vendor/bin/phpcs --standard=PSR12 src --ignore=./src/Kernel.php
  - vendor/bin/phpmd src html ./phpmd.xml.dist
  - vendor/bin/phpcpd src
	- vendor/bin/phpcs --standard=PSR1  tests
	- vendor/bin/phpcs --standard=PSR2  tests
  - vendor/bin/phpcs --standard=PSR12 tests
  - vendor/bin/phpmd tests html ./phpmd.xml.dist
  - vendor/bin/phpcpd tests
  - bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
