language: php

php: 
  - '7.3'

services: 
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

install: |
  composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

dist: trusty

sudo: required

before_script:
  - mysql -e 'create database oai;'

script: 
  - bin/console doctrine:database:create --if-not-exists
  - bin/console doctrine:schema:create
  - bin/console doctrine:schema:update --force
  - bin/console doctrine:fixtures:load --append
  - bin/phpunit